import type { Metadata } from "next";
import "./globals.css";

import { Grandstander } from "next/font/google";

const grandstander = Grandstander({
  subsets: ["latin"],
  variable: "--font-grandstander",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${grandstander.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
