export const ACTIONS_OBJECT = [
  {
    code: "write_a_haiku",
    name: "Write a Haiku",
    shortName: "haiku",
    asAction: "wrote a haiku",
    emoji: "✍️",
    color: "blue",
  },
  {
    code: "tweet_an_idea",
    name: "Tweet an Idea",
    shortName: "idea",
    asAction: "tweeted an idea",
    emoji: "💡",
    color: "yellow",
  },
  {
    code: "tweet_a_wojak_meme",
    name: "Tweet a Wojak Meme",
    shortName: "wojakmeme",
    asAction: "tweeted a Wojak meme",
    emoji: "😎",
    color: "red",
  },
  {
    code: "tweet_a_feeling",
    name: "Tweet a Feeling",
    shortName: "feeling",
    asAction: "tweeted a feeling",
    emoji: "🙂",
    color: "teal",
  },
  {
    code: "learn_something_new",
    name: "Learn Something New",
    shortName: "learn",
    asAction: "learned something new",
    emoji: "📚",
    color: "green",
  },
  {
    code: "release_a_side_hustle",
    name: "Release a Side Hustle",
    shortName: "sidehustle",
    asAction: "released a side hustle + article",
    emoji: "🚀",
    color: "orange",
  },
  {
    code: "travel_to_a_new_place",
    name: "Travel to a New Place",
    shortName: "travel",
    asAction: "traveled to a new place",
    emoji: "✈️",
    color: "purple",
  },
  {
    code: "create_art_nft",
    name: "Create Art NFT",
    shortName: "art",
    asAction: "created an art NFT",
    emoji: "🎨",
    color: "emerald",
  },
  // {
  //   code: "take_a_selfie",
  //   name: "Take a Selfie",
  //   shortName: "selfie",
  //   asAction: "took a selfie",
  //   emoji: "🤳",
  //   color: "indigo",
  // },
  {
    code: "something_amazing_happens",
    name: "Something Amazing Happens",
    shortName: "amazing",
    asAction: "experienced something amazing",
    emoji: "✨",
    color: "white",
  },
  {
    code: "something_terrible_happens",
    name: "Something Terrible Happens",
    shortName: "terrible",
    asAction: "experienced something terrible",
    emoji: "😱",
    color: "black",
  },
  {
    code: "tweet_a_dad_joke",
    name: "Tweet a Dad Joke",
    shortName: "dadjoke",
    asAction: "tweeted a dad joke",
    emoji: "😂",
    color: "zinc",
  },
  {
    code: "share_a_photo_of_where_you_are",
    name: "Share a Photo of Where You Are",
    shortName: "photo",
    asAction: "shared a photo",
    emoji: "📸",
    color: "pink",
  },
  {
    code: "win_an_award",
    name: "Win an Award",
    shortName: "award",
    asAction: "won an award",
    emoji: "🏆",
    color: "amber",
  },
  // {
  //   code: "send_money_to_a_friend",
  //   name: "Send Money to a Friend",
  //   shortName: "money",
  //   asAction: "sent money to a friend",
  //   emoji: "💰",
  //   color: "emerald",
  // },
  // {
  //   code: "send_money_to_the_government",
  //   name: "Send Money to the Government",
  //   shortName: "taxes",
  //   asAction: "sent money to the government",
  //   emoji: "💰",
  //   color: "emerald",
  // },
  {
    code: "someone_buys_something_from_you",
    name: "Someone Buys Something from You",
    shortName: "sell",
    asAction: "sold something",
    emoji: "💰",
    color: "emerald",
  },
  {
    code: "you_buy_something_from_someone_else",
    name: "You Buy Something from Someone Else",
    shortName: "buy",
    asAction: "bought something",
    emoji: "💰",
    color: "emerald",
  },
  {
    code: "tweet_a_pixel_art_nft",
    name: "Tweet a Pixel Art NFT",
    shortName: "pixelart",
    asAction: "tweeted a pixel art NFT",
    emoji: "🎨",
    color: "emerald",
  },
] as {
  code: string;
  name: string;
  shortName: string;
  asAction: string;
  emoji: string;
  color: string;
}[];

export const INDIVIDUAL_ACTIONS = [
  // "send_a_voice_note",
  //   "tweet_a_random_thought",
  //   "buy_a_service_from_the_marketplace",
  //   "put_a_service_on_the_marketplace",
  //   "quote_a_tweet_from_someone_else",
  //   "create_an_image_and_launch_it_as_an_nft",
  //   "fall_in_love_with_another_clone",
  //   "get_fired_from_a_job",
  //   "get_a_new_job",
  //   "get_married",
  //   "have_kids",
  //   "create_songs_with_suno",
  //   "create_a_new_pfp",
  //   "buy_an_nft_from_someone_else",
];
