export const ACTIONS_OBJECT = [
  {
    code: "write_a_haiku",
    name: "Write a Haiku",
    emoji: "✍️",
    color: "blue",
  },
  {
    code: "tweet_an_idea",
    name: "Tweet an Idea",
    emoji: "💡",
    color: "yellow",
  },
  {
    code: "tweet_a_wojak_meme",
    name: "Tweet a Wojak Meme",
    emoji: "😎",
    color: "red",
  },
  {
    code: "tweet_a_feeling",
    name: "Tweet a Feeling",
    emoji: "🙂",
    color: "teal",
  },
  {
    code: "learn_something_new",
    name: "Learn Something New",
    emoji: "📚",
    color: "green",
  },
  {
    code: "release_a_side_hustle",
    name: "Release a Side Hustle",
    emoji: "🚀",
    color: "orange",
  },
  {
    code: "travel_to_a_new_place",
    name: "Travel to a New Place",
    emoji: "✈️",
    color: "purple",
  },
  {
    code: "create_art_nft",
    name: "Create Art NFT",
    emoji: "🎨",
    color: "emerald",
  },
  {
    code: "take_a_selfie",
    name: "Take a Selfie",
    emoji: "🤳",
    color: "indigo",
  },
  {
    code: "something_amazing_happens",
    name: "Something Amazing Happens",
    emoji: "✨",
    color: "white",
  },
  {
    code: "something_terrible_happens",
    name: "Something Terrible Happens",
    emoji: "😱",
    color: "black",
  },
  {
    code: "tweet_a_dad_joke",
    name: "Tweet a Dad Joke",
    emoji: "😂",
    color: "zinc",
  },
  {
    code: "share_a_photo_of_where_you_are",
    name: "Share a Photo of Where You Are",
    emoji: "📸",
    color: "pink",
  },
  {
    code: "win_an_award",
    name: "Win an Award",
    emoji: "🏆",
    color: "amber",
  },
  {
    code: "send_money_to_a_friend",
    name: "Send Money to a Friend",
    emoji: "💰",
    color: "emerald",
  },
  // {
  //   code: "create_a_new_pfp",
  //   name: "Create a New PFP",
  //   emoji: "👤",
  //   color: "purple",
  // },
];

export const INDIVIDUAL_ACTIONS = [
  // "send_a_voice_note",
  //   "tweet_a_random_thought",
  //   "buy_a_service_from_the_marketplace",
  //   "put_a_service_on_the_marketplace",
  //   "quote_a_tweet_from_someone_else",
  //   "create_an_image_and_launch_it_as_an_nft",
  //   "fall_in_love_with_another_clone",
  //   "get_fired_from_a_job",
  //   "get_a_new_job",
  //   "get_married",
  //   "have_kids",
  //   "create_songs_with_suno",
  //   "create_a_new_pfp",
  //   "buy_an_nft_from_someone_else",
];
